### PR TITLE
(MODULES-6781) Update Rakefile to allow disabling Lint rules

### PR DESCRIPTION
**Pull request by HelenCampbell**

### CODE REVIEW

**Comment by HelenCampbell** [comment]
Tested against NTP:
`142 --- Rakefile  2017-12-20 14:54:02.697852433 +0000
143 +++ Rakefile.pdknew 2018-03-12 11:56:56.787121000 +0000
144 @@ -1,3 +1,6 @@
145  require 'puppetlabs_spec_helper/rake_tasks'
146  require 'puppet-syntax/tasks/puppet-syntax'
147 +
148 +PuppetLint.configuration.send('relative')
149 +PuppetLint.configuration.send('disable_only_variable_string')`

**Comment by HelenCampbell** [comment]
The 'relative' configuration has been defined in config_defaults and has never been used as the Rakefile wasn't configured. This PR addresses that alongside giving the functionality of disabling lint cops.

**Comment by pmcmaw** [comment]
+1 👍

**Comment by bmjen** [comment]
@HelenCampbell @pmcmaw can you paste an example of what the `.sync.yml` would look like for configuring this?

Also, it needs docs update to the README to add the extra configuration options.

**Comment by pmcmaw** [comment]
.sync.yml would contain an entry that would look similar to this (depending on the lint rule you are disabling. We will work on docs tomorrow. :-)
```
Rakefile:
  extra_disabled_lint_checks:	  
    - 'disable_only_variable_string'
```

**Pull request merged**
