### PR TITLE
metadata-json-lint: Switch to 4.x

### PR DESCRIPTION
**Pull request by bastelfreak**
## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified.

### CODE REVIEW

**Comment by jordanbreen28** [comment]
hey @bastelfreak - could you address the conflict and we'll get this merged?

**Comment by bastelfreak** [comment]
@jordanbreen28 rebased it. I currently don't have a pdk test environment, so it might be good if someone could test it.

**Comment by bastelfreak** [comment]
@jordanbreen28 and is there a chance you could test puppetlabs_spec_helper 7? pdk-templates still uses the old 6 release.

**Comment by jordanbreen28** [comment]
@bastelfreak That's great, thanks! I'll take it for a spin before merging, hopefully soon.
RE puppetlabs_spec_helper v7, it caused some issues with the last pdk release so we had to pin down to ~> 6.0, theres a ticket on the backlog about to be brought in and it'll be bumped back up the latest by the time the pdk-templates are tagged next :)

**Review by jordanbreen28 — APPROVED** [review]
tested and verified locally.
thanks @bastelfreak

**Pull request merged**
