### PR TITLE
(fix) Set rubocop ruby version to 2.4

### PR DESCRIPTION
**Pull request by tuxmea**
2.1 has some changes to hash syntax.
using 2.1 shows false positives

### CODE REVIEW

**Review by DavidS — CHANGES_REQUESTED** [review]
Hi @tuxmea ,

1) as it is this seems to be breaking `pdk validate` 
2) as long as we have to support puppet4/ruby2.1 this will create incompatible code or failing validations

**Comment by tuxmea** [comment]
rubcop complained about wrong ruby version, only up to 2.4 is accepted.

**Comment by tuxmea** [comment]
> Hi @tuxmea ,
> 
>     1. as it is this seems to be breaking `pdk validate`

Fixed.
> 
>     2. as long as we have to support puppet4/ruby2.1 this will create incompatible code or failing validations

Support Puppet 4? Are you sure?

**Comment by DavidS** [comment]
https://github.com/puppetlabs/pdk-vanagon/pull/268 is currently in progress to remove puppet4 and ruby 2.1 from pdk. That'll unblock this work.

**Review by DavidS — APPROVED** [review]

**Comment by DavidS** [comment]
the pdk change got merged, so this is unblocked. Since I'm away next week, I'll leave it to the team to merge on Community Monday.

**Review by sanfrancrisko — APPROVED** [review]

**Pull request merged**
