### PR TITLE
Add support for custom docker images

### PR DESCRIPTION
**Pull request by Odiobill**
New pull request for this specific change after the comments on the previous one.

### CODE REVIEW

**Comment by bmjen** [comment]
CC @npwalker @jarretlavallee

**Comment by npwalker** [comment]
@bmjen I think this partially solves the problem and allows adding in your own docker image but since the loop is based on ruby version and the ruby version was coming from the docker image it seems like an unreliable solution.  

Granted a more reliable solution would probably result in a breaking change or we'd have to have two separate code paths based on whether ruby_version was supplied ( or something like that).

**Comment by ghoneycutt** [comment]
This PR seems very straight forward. Why not merge it or close it.

**Comment by scotje** [comment]
Seems like this was resolved by #137, please let us know if not.

**Pull request closed without merging**
