### PR TITLE
Finalise auto-release-prep using pdk-docker image and cleanup artifacts

### PR DESCRIPTION
**Pull request by carabasdaniel**

### CODE REVIEW

**Comment by carabasdaniel** [comment]
Resulting PR from test: https://github.com/puppetlabs/puppetlabs-testing/pull/343
GA: https://github.com/puppetlabs/puppetlabs-testing/actions/runs/540119989

**Review by DavidS — CHANGES_REQUESTED** [review]
Clicked through to the honeycomb trace and there's a missing span. Needs a final recording step like https://github.com/puppetlabs/pdk-templates/blob/ec9c1296ef7e6efa2ba7a47fbc4ad3836074b1f4/moduleroot/.github/workflows/nightly.yml.erb#L72-L75

**Review by sheenaajay — DISMISSED** [review]

**Comment by DavidS** [comment]
apologies for not noticing earlier:
https://github.com/puppetlabs/puppetlabs-testing/pull/343/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR76 

Commits the addition of the PDK into the release. Would using the pdk-docker image be a way around that?

**Comment by DavidS** [comment]
or do we need to bite the bullet and make `pdk release prep` a full action?

**Review by DavidS — APPROVED** [review]

**Pull request merged**
