### PR TITLE
Updates for ruby 2.4 and rubocop 1.6.1

### PR DESCRIPTION
**Pull request by DavidS**
* update profile_builder to work with ruby 2.7
* stabilize the default_enabled_cops output
* remove rubocop-i18n
* update to rubocop-1.6.1 and rubocop-rspec 2.0.1
* add a 1.6.1 defaults file
* ignore erroneous `Lint/Syntax` config
* disable the Style/NumericPredicate as it causes some churn and is not enforcing the status quo
* Remove GetText cop configurations
* drop 0.49.1 defaults - impossible to keep compatible configs across the ages
* update a number of cops to new names
* re-add split off rubocop-performance
* add newer Performance cops
* drop manual pins for rubies before 2.4
* bump puppet-module-gems to 1.0 (about to be released)

### CODE REVIEW

**Comment by DavidS** [comment]
see https://github.com/puppetlabs/puppetlabs-panos/pull/126 for example results

**Comment by DavidS** [comment]
see https://github.com/puppetlabs/pdk-templates/pull/373 for a run passing against locally built gems on cloudsmith

**Comment by DavidS** [comment]
More testing: https://github.com/puppetlabs/puppetlabs-testing/pull/325

**Comment by DavidS** [comment]
> More testing:
>     * [puppetlabs/puppetlabs-testing#325](https://github.com/puppetlabs/puppetlabs-testing/pull/325)
>     * [puppetlabs/puppetlabs-accounts#354](https://github.com/puppetlabs/puppetlabs-accounts/pull/354)
>     * [puppetlabs/puppetlabs-acl#225](https://github.com/puppetlabs/puppetlabs-acl/pull/225)

Re-ran those three PRs against the tip of this PR (without gem testing source) using the released gem versions - all green!

**Review by michaeltlombardi — APPROVED** [review]

**Pull request merged**
