### PR TITLE
(PDK-944) Enforce WordArray brackets style

### PR DESCRIPTION
**Pull request by jearls**
See https://tickets.puppetlabs.com/browse/PDK-944

### CODE REVIEW

**Comment by dhollinger** [comment]
This looks like a good solution to me

**Comment by jearls** [comment]
this looks fine to me as well.  my only concern is changing the enforced style rather than un-enforcing it.  in SemVer, this would be the sort of thing that requires a major version change, so i was trying to avoid that myself.

**Comment by DavidS** [comment]
@bmjen I think this can move forwards.

**Comment by jearls** [comment]
rebased off current master

**Comment by jearls** [comment]
Thanks!

**Pull request merged**
