### PR TITLE
(FM-7709) include litmus rake tasks if gem exists

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by glennsarti** [comment]
Just curious why the docs change?

**Comment by tphoney** [comment]
> Just curious why the docs change?

That is no longer relevant, @DavidS ran across this yesterday. If you want beaker gems, include puppet-module-posix-system-r* and / or puppet-module-win-system-r* They are now part of puppet-module-gems.

**Comment by tphoney** [comment]
https://github.com/puppetlabs/puppetlabs-stdlib/pull/1027
https://github.com/puppetlabs/puppetlabs-acl/pull/149
https://github.com/puppetlabs/puppetlabs-iis/pull/224

**Comment by tphoney** [comment]
all passing travis/appveyor pr tests

**Comment by tphoney** [comment]
all tests passing through adhoc, screengrabs in the pr's

**Pull request merged**
