### PR TITLE
puppetlabs_spec_helper: Require 7.X

### PR DESCRIPTION
**Pull request by bastelfreak**
We're using this since some time at Vox Pupuli and I think Puppet should also use the latest version of their own software. Tested for development group in https://github.com/puppetlabs/puppetlabs-apt/blob/main/Gemfile#L26

### CODE REVIEW

**Comment by bastelfreak** [comment]
https://github.com/puppetlabs/puppetlabs-apt/actions/runs/7916102903/job/21609282764 and this uses psh 7 for a release.

**Comment by bastelfreak** [comment]
Is that a public pipeline?

**Comment by david22swan** [comment]
Ah, disregard the above comment sorry, ran a clean image and the failures have migrated there. Just unfortunate timing on their appearance it seems.

**Comment by bastelfreak** [comment]
@david22swan is there any update on this? I need the newer puppetlabs_spec_helper for a few customers.

**Comment by david22swan** [comment]
@bastelfreak Still working on failures on the PDK sorry.
The original ones I last mentioned have been resolved however new ones appeared following that.

**Comment by bastelfreak** [comment]
What kind of errors? something we can help with?

**Comment by david22swan** [comment]
@bastelfreak Sorry for the wait on this, but we've got the PDK back into working order so I am happy to merge.
I've already done some preliminary testing so if you can resolve the conflict that has appeared during the wait I can merge immeaditely.

**Comment by bastelfreak** [comment]
@david22swan rebased it

**Review by david22swan — APPROVED** [review]
LGTM

**Pull request merged**
