### PR TITLE
(packaging) Enable puppet-lint-plugins also on Windows #468

### PR DESCRIPTION
**Pull request by ConradGroth**

### CODE REVIEW

**Comment by ConradGroth** [comment]
I tested this change locally on Windows 10 with PDK 2.4.0 (using Ruby 2.5.9 and Puppet 6.26.0). It runs perfectly and now I get the same warnings as under Linux.

**Comment by ConradGroth** [comment]
@bastelfreak WDYT? The original addition of the puppet-lint-plugins with the restriction to platform ruby was made by you two months ago.

**Comment by bastelfreak** [comment]
I think I did that because I had no Windows to test it.

**Review by david22swan — APPROVED** [review]
This change look's good to me and seems to run fine.
Going to go ahead and merge.
Thanks for putting the work in :)

**Pull request merged**
