### PR TITLE
(maint) Add global_env section to Travis configuration

### PR DESCRIPTION
**Pull request by jearls**
Allow configuration of Travis `global` environment variables through the addition of a new `global_env` section in the travis configuration.
The existing `env` section is modified to add its environment variables to the `matrix` section of Travis's `env` settings (to keep identical behavior to the existing functionality).
See https://docs.travis-ci.com/user/environment-variables/#Global-Variables

### CODE REVIEW

**Comment by bmjen** [comment]
Thanks @jearls can you add docs to the README with these new config options?

**Comment by jearls** [comment]
@bmjen, updated the README to include the following, which documents the `global_env` setting and corrects (or at least _clarifies_) the documentation for the `env` setting:

| Key            | Description   |
| :------------- |:--------------|
| env            |Allows you to add new travis job matrix entries based on the included environmnet variables, one per `env` entry; for example, for adding jobs with specific `PUPPET_GEM_VERSION` and/or `CHECK` values.  See the [Travis Environment Variables](https://docs.travis-ci.com/user/environment-variables) documentation for details.|
| global_env     |Allows you to set global environment variables which will be defined for all travis jobs; for example, `PARALLEL_TEST_PROCESSORS` or `TIMEOUT`.  See the [Travis Global Environment Variables](https://docs.travis-ci.com/user/environment-variables/#Global-Variables) documentation for details.|

**Comment by jearls** [comment]
@bmjen Are the new docs sufficient?

**Comment by jearls** [comment]
Thank you!

**Pull request merged**
