### PR TITLE
(PDK-1210) setting inherited const_defined lookup to false

### PR DESCRIPTION
**Pull request by Thomas-Franklin**
If there is a top level module with same name as a type which gets loaded before the type gets defined.

This will trigger a false positive on the `last_module.const_defined?` check causing an `uninitialized constant` error.

This change will no longer do a recursive check and only care about the local namespace this way avoiding the false positive.

### CODE REVIEW

**Comment by DavidS** [comment]
See also https://github.com/puppetlabs/puppet-resource_api/pull/132 and https://github.com/puppetlabs/puppet-resource_api/pull/134.

**Comment by davidmalloncares** [comment]
@Thomas-Franklin - has there been any movement on this one recently?

**Comment by Thomas-Franklin** [comment]
> @Thomas-Franklin - has there been any movement on this one recently?

@davidmalloncares it was approved by @scotje, but not sure if it needs more than one approval. I'll update the branch with master and have it ready anyway.

**Comment by scotje** [comment]
Seeing if @bmjen or @rodjek can take a look, we typically do 2 reviews before merge.

**Pull request merged**
